### PR TITLE
Remove references to hh5, build new analysis3 to prepare access-nri-intake release

### PR DESCRIPTION
**Pull request by rbeucher**

### CODE REVIEW

**Comment by rbeucher** [comment]
Using pip install for intake-ESM leads to:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
intake-thredds 2024.3.1 requires intake<2,>=0.6.6, but you have intake 2.0.7 which is incompatible.
```

**Comment by rbeucher** [comment]
Actually, that's wrong `intake-thredds` is causing the issue. 
@charles-turner-1, do we need it?
I am not sure I can remove it though...That env is supposed to replace hh5

**Comment by rbeucher** [comment]
Intake has ` intake.readers.catalogs.THREDDSCatalogReader`
Maybe it replaces `intake-thredds`?

**Comment by charles-turner-1** [comment]
I've had a look in all of the intake related environments (access-nri-intake-catalog, intake-dataframe-catalog, intake-esm) and I can't find intake-thredds in any of them, so I don't think it's being pulled in via the dependency tree of one of those.

I suspect it's probably fine to remove but I'm gonna do a bit more digging - I think it's worth finding out how it got included before we remove it.


Screenshot 2024-11-28 at 12 29 39 PM

**Comment by charles-turner-1** [comment]
Looks like an explicit requirement in `environments/analysis3/environment.yml`.

Since I can't see any dependencies on it, and grepping the python code for any references to `open_thredds_cat` or similar turns up nothing, I think we're safe to remove it.

**Pull request merged**
