### PR TITLE
Promote access-nri-intake to 1.0.0b2 in analysis3

### PR DESCRIPTION
**Pull request by marc-white**
This PR is in prep to update the `analysis3` environment to use the new beta release of `access-nri-intake-catalog` `v1.0.0b2`.

### CODE REVIEW

**Comment by rbeucher** [comment]
Did you cancel the checks?

**Comment by marc-white** [comment]
Yep, checks cancelled once I saw them starting.

**Comment by marc-white** [comment]
Package now built, restarting checks...

**Comment by rbeucher** [comment]
I had to manually restart the failed conda build. Looks like there is a delay between the push to pypi and the download from the conda build action...

**Comment by marc-white** [comment]
Looks like it's set to go @rbeucher

**Comment by marc-white** [comment]
> I had to manually restart the failed conda build. Looks like there is a delay between the push to pypi and the download from the conda build action...

It's weird, I checked last night when it was failing, and I could find the 1.0.0b2 version on PyPI while the conda build was still complaining.

**Comment by rbeucher** [comment]
Something to keep an eye on.

**Pull request merged**
